### ISSUE TITLE
Having alias entity name for GraphQL schema

### ISSUE THREAD

**Issue by chanhengseang3** [introproventures/graphql-jpa-query#110]
I have trouble on build schema with these kind of entity :
* Entity's name ended with `es` (whenever `atteo.English`  try to convert it, it return original name , then schema will have duplicate type )
* Entity with duplicate name (there are some cases that there are entity with same name in different package and different table name)

I think alias name  on entity can fix this issues.

**Comment by igdianov** [comment]
@chanhengseang3 You customize entity names in GraphQL schema using `@Entity("name")` to resolve duplicate class name conflicts. Can you post minimal example that causes problems?

The pluralizer library is not perfect. It is probably a good idea to be able override that with `@GraphQL` annotation attributes.

**Comment by chanhengseang3** [comment]
* I have one Entity Named: `DepositAccountInterestIncentives` , it gives error said there are duplicate type name , types in GraphQL schema are unique.
* i have `/java/../a/../Template.java` and `/java/../b/../Template.java` , returning same error.

**Comment by igdianov** [comment]
@chanhengseang3 As I mentioned you can try to use JPA's `@Entity("alias")` annotation to resolve same name collision in GraphQL schema, i.e.

in a.Template.java use `@Entity("TemplateA") and in b.Template.java use `@Entity("TemplateB")`. This will generate GraphQl types with different names. You can also post a stack trace of the error to help me figure it out...

**Comment by chanhengseang3** [comment]
Thank you! problem solved.
