### ISSUE TITLE
Question: Select only the columns requested by the graphql query

### ISSUE THREAD

**Issue by Thihup** [introproventures/graphql-jpa-query#114]
Currently the JPA query select all columns of an entity. 
It would be possible to just select the requested fields?

**Comment by igdianov** [comment]
@Thihup There is entity fetch graph provided in the query to persistence provider with only requested fields from the GraphQL query. It works as a hint for persistent provider implementation, i.e. Hibernate to generate SQL query that retrieves only requested fields. The persistence provider decided how to generate SQL query and map it to the objects.

**Comment by molexx** [comment]
For reference, this is a known bug in Hibernate: https://hibernate.atlassian.net/browse/HHH-8776

**Comment by anotender** [comment]
@igdianov Is it possible to resign from adding fetchgraph hint in favor of building the multiselect clause in `QraphQLJpaBaseDataFetcher#getQuery` by ourselves? Has it ever been considered? I've tried amending the code around there but I have troubles with properly mapping the result to the GraphQL result. I am not sure how much effort will it require.
