### ISSUE TITLE
Should nested where criteria restrict nested data returned?

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#122]
Lets say I wanted to find all characters who appear in A_NEW_HOPE. This is straightforward:

```
query {
  Characters (where: {appearsIn :{IN:A_NEW_HOPE}}){
    select {id, name}
  }
}
```

Then if I wanted to include `appearsIn` in the results along with `id` and `name`, would you expect that array to be the full array of all films they appear in or would you expect just one item in the array - `A_NEW_HOPE`?

I'm not sure.

Currently it only returns the one item. It isn't a problem for me right now but I could see a case where it might be - in that scenario you'd have to collect the character IDs and make a second query.

**Comment by igdianov** [comment]
@molexx Thanks for the catch!
