### ISSUE TITLE
Explore injecting where argument via variables

### ISSUE THREAD

**Issue by igdianov** [introproventures/graphql-jpa-query#126]
so, that `where` argument can be constructed dynamically at runtime if needed, i.e.

```
query($where: HumansCriteriaExpression) {
  Humans (where: $where) {
    select {
      id(orderBy: ASC)
      name
    }
  }
}
```
with query variables:

```
{
  "where": { 
    "appearsIn": {
      "IN": ["A_NEW_HOPE", "EMPIRE_STRIKES_BACK"]}
  }
}
```

**Comment by Thihup** [comment]
I really need this feature. Could you please implement it @igdianov?

**Comment by anotender** [comment]
Hi @igdianov,

Have you had a chance to investigate the issue? From what I saw, it looks like there are 2 possibilities:
1. We can try to adjust the [QraphQLJpaBaseDataFetcher.getValue](https://github.com/introproventures/graphql-jpa-query/blob/master/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java#L381) and build the proper where value object using the passed variables Map and traverse entityType looking for proper property types.
2. Try to somehow build the graphql query from variables json and replace it in the actual query string in the place where the $where variable reference has its place.

Unfortunately, none of these solutions looks good enough. Do you possibly know if there are any other approaches that can be checked?

**Comment by igdianov** [comment]
@anotender Thank you for you comment. I am a bit busy with another project at the moment, but if you want to start a PR to make a contribution, you are very welcome to do so. 

The best approach is to make a unit test that blows up and then try to figure out how properly resolve complex argument values from `DataFetchingEnvironment` using `graphql-java` Api before building query. After the argument values are resolved, they can be used to augment original `DataFetchingEnvironment` object to build the query using resolved values.

**Comment by anotender** [comment]
@igdianov great, thanks for help! In such case I'll try to proceed with the development and publish my PR shortly so you can have a look and check if it is valid.

**Comment by anotender** [comment]
@igdianov is it possible to add me as a collaborator to the project so I can create a branch and push changes?

**Comment by igdianov** [comment]
@anotender You can start a PR for your fork if you want to make any changes. This is the best way.

**Comment by anotender** [comment]
@igdianov sure, I'll add my test cases to your branch on my fork repo and will link it here so you can have a look at it
