### ISSUE TITLE
Getter/Setter of @Transient field return "type can't be null" error

### ISSUE THREAD

**Issue by chanhengseang3** [introproventures/graphql-jpa-query#142]
I have tried @Transient on basic Java type like `String` or `Int` , it works ok.
But when i try @Transient on field with Java Class type having getter/setter , it return error.
```
    @Transient
    private Office office;
    public Office getOffice(){...}
```
This will return "type can't be null" exception.

**Comment by igdianov** [comment]
Fixed via https://github.com/introproventures/graphql-jpa-query/pull/173
