### ISSUE TITLE
Help! Bug? How to query timestamp columns? 

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#150]
I am trying to query a JPA entity with a datetime column eg 

   @Column(name = "EFFECTIVE_END_TSTAMP")
    @Temporal(TemporalType.TIMESTAMP)
    private Date effectiveEndTimestamp;

However if I pass the following to my query:

effectiveEndTimestamp: { EQ : "2009-12-31T13:02:03"}

this gets converted to a date,  losing the time information when performing the query, due to the GraphQLDateCoercing formatting to "yyyy-MM-dd".

I noticed that the JavaScalars class has a coercion for LocalDateTime, so I tried switching my JPA entity to use LocalDateTime instead of Date. However if I do this I then get an IllegalArgumentException thrown from JpaPredicateBuilder saying that LocalDateTime is not supported, and looking at the source code for JpaPredicateBuilder indeed only the Date type seems to be supported. 

Is there a way of doing this, or is this a bug in the framework?

**Comment by MurrayFurtado** [comment]
I managed to resolve this issue myself by overwriting the default Date.class scalar registered as follows:

**Comment by SinaiNIN** [comment]
@MurrayFurtado It doesn't work

**Comment by SinaiNIN** [comment]
@MurrayFurtado I tried as you did, but it error
```
      "message": "Validation error of type WrongType: argument 'where.createdDate.EQ' with value 'StringValue{value='2019-07-25T08:15:20.000+0000'}' is not a valid 'Date'
```

**Comment by MurrayFurtado** [comment]
Your date format is incorrect. You need a : in your timezone ie - +00:00
I also discovered if you are using multiple datasources, you have to register the GraphQLScalarType with a unique name eg. "DateTime1","DateTime2", etc as otherwise it throws an error.
