### ISSUE TITLE
Enhancement request to allow predicates in joins.

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#152]
Is it possible to generate queries with the framework which allow predicates in joins, ie results in SQL being generated like the below:

select ...
From Position pos
inner join Portfolio port on (pos.portfolio_id = port.portfolio_id and port.current_flag = 'y')
left outer join Security sec on (pos.security_id = sec.security_id and sec.current_flag = 'y')

As far as I can tell this feature is available in Hibernate via the @Where annotation.

**Comment by igdianov** [comment]
@MurrayFurtado This is a proprietary Hibernate annotation. The library only uses JPA 2.1 specification and APIs to transform GraphQL queries into JPA Criteria queries.
