### ISSUE TITLE
GraphQLIgnore is checked against Methods but cannot be applied to them

### ISSUE THREAD

**Issue by Syreniac** [introproventures/graphql-jpa-query#153]
I have a somewhat dated model implementation that includes some data that I cannot easily expose via GraphQL, and this causes problems when creating the schema due to the unmappable types. To avoid this, I went through and annotated all the relevant fields with the @GraphQLIgnore annotation. For example (as a cut down version of this problem):

```
@Entity
public class UnGraphqlableEntity{

	// Locales are currently not included in graphql's implementation
	@GraphQLIgnore
	private Locale locale;
	
	public void setLocale(Locale locale){
		this.locale = locale;
	}
	
	public Locale getLocale(){
		return locale;
	}

}
```

When I made all these changes and started the application, it gave back the same errors. Debugging down to GraphQLJpaSchemaBuilder.isNotIgnored() showed that what was happening was that the field types and the field accessor methods were being checked for the annotation but not the actual field itself. 

As a temporary change I added the METHOD target type to the GraphQLIgnore annotation and applied this to the relevant getter methods, which fixed the problem while I was able to work on a temporary snapshot version. Trying to re-align myself with the main release versions is causing this problem to re-occur however, and the fix seems relatively minor.

**Comment by igdianov** [comment]
@Syreniac You are welcome to make a PR to solve this problem for yourself and other users.
