### ISSUE TITLE
Transient fields are not excluded by default from the built schema

### ISSUE THREAD

**Issue by Syreniac** [introproventures/graphql-jpa-query#154]
I have a somewhat dated model implementation that includes some transient methods that I do not want to expose via GraphQL, For example (as a cut down version of this problem):

```
@Entity
public class GraphqlableEntity{

	private String value;
	
	public void setValue(Locale locale){
		this.value = value;
	}
	
	public Locale getValue(){
		return value;
	}

        @Transient
        public String doThing(){
            // Exact body doesn't matter
        }

}
```

Realistically Transient methods should not be included in the graphql schema because it likely makes no sense to query for the values expressed by them (unfortunately I can't simply remove these due to them being required for a substantial amount of legacy code). Arguably they could be annotated with @GraphQLIgnore, but this is a maintenance burden that could be avoided if the check in GraphQLJpaSchemaBuilder.isNotIgnored() took @Transient into account as well.

**Comment by igdianov** [comment]
@Syreniac Sounds good to me! I will add support for `@Transient` annotation to exclude such fields.

**Comment by anotender** [comment]
@igdianov @Syreniac I am not sure if we want to exclude transient fields by default. What do you think? Such behaviour should be configurable in my opinion. Wha do you think?

There is something more I found regarding transient fields. When there is a transient method returning some complex type like e.g. entity then it is not mapped correctly in response.
```java
@Entity
public class Comment { /*...*/ }

@Entity
public class Post {
    //...
    @Transient
    public Comment getLastComment(){ /*...*/ }
}
```
Is it possible in any way to make schema aware that the return type is another entity?

**Comment by igdianov** [comment]
I agree that excluding transient fields by default is not a good idea. We could use GraphQL Schema transformation after build to apply a filter function for any transient fields.

@anotender I think the best approach to address complex return type is to use add support for custom output type builder with ObjectScalar as default.
