### ISSUE TITLE
Fails on bean properties starting with upper case

### ISSUE THREAD

**Issue by pierrefoyard** [introproventures/graphql-jpa-query#172]
Hi,
My Database contains columns starting with uppercase (for example "Folder_ID").
We keep these column names in JPA beans, so we have beans like:

```
@Getter
public class MyBean {
  private Integer Folder_Id;
}
```
This leads to fatal exception in GraphQLSchemaFactoryBean at parsing stage.
I get this issue with 0.3.28 and 0.3.29-SNAPSHOT.
In debug mode I noticed that this problem comes from the fact that in GraphQLJpaSchemaBuilder::getEntityAttributesFields we loop on entity attributes (attribute name is "Folder_Id" in my example). Then in sub function IntrospecutionUtils::isIgnored, we search for attribute name in descriptors map built in EntityIntrospectionResult based on beanInfo;getPropertyDescriptors. This map is built based on getter names and removes first upper case letter (except when the second lettre is also in upper case). So this map contains an entry "folder_Id" and because we cannot find our attribute name we get an exception.

Best regards,

Pierre.

**Comment by igdianov** [comment]
Thanks for reporting the issue. I will look into it to find a workaround.
