### ISSUE TITLE
Error querying entity with @IdClass

### ISSUE THREAD

**Issue by francescopace** [introproventures/graphql-jpa-query#176]
I've an entity bean with @IdClass annotation (multiple id columns).
This kind of annotation is not well supported by this framework and every query will fail due to:

https://github.com/introproventures/graphql-jpa-query/blob/82be5d5e3773923119cc549052875e6f9e3ee050/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java#L190

You should change that, to something like this:

```java
        if(entityType.hasSingleIdAttribute()){
            SingularAttribute<?,?> idAttribute = entityType.getId(Object.class);
            ...
        }else{
            ...
        }
```
Alternatively you can delete that line and change query statement 

https://github.com/introproventures/graphql-jpa-query/blob/82be5d5e3773923119cc549052875e6f9e3ee050/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java#L192

in

```java
query.select(cb.count(root));
```

**Comment by igdianov** [comment]
Thank you for feedback and the tip. I will take a look at it tomorrow
