### ISSUE TITLE
Error in GQL Queries when `total` or `pages` is included with condition `where: NOT_EXISTS` or `EXISTS`

### ISSUE THREAD

**Issue by SinaiNIN** [introproventures/graphql-jpa-query#193]
We able to get query result at least `null array`  if we do not provide condition `where: NOT_EXISTS or EXISTS`. But if we provide with `where: NOT_EXISTS or EXISTS` then result will be default `error`.

**Comment by igdianov** [comment]
@SinaiNIN Thank you for PR with failing test. I will take a look at it
