### ISSUE TITLE
Feature request: Metrics Instrumentation Hook

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#197]
Hi, 

I need to send metrics around my graphql queries to InfluxDb / Grafana.  Do you have a hook that I can attach to before / after the query is run so that I might capture metrics? Or a recommended approach to doing this?

Thanks

**Comment by igdianov** [comment]
@MurrayFurtado It is possible to post-process `GraphQLSchema` to add any instrumentation for tracing, authorization, or metrics export. This could be done per request, session, or once for application start using the following technique to transform existing schema using Graphql-java Api. See the following example in this PR to add instrumentation per request: https://github.com/introproventures/graphql-jpa-query/pull/163/files#diff-adcb0c1a00d288ec1c4565bec7474db3R93

You can implement your own `GraphQLJpaExecutorContextFactory` bean that will plug your instrumentation into GraphQL query execution, instead of default implementation: https://github.com/introproventures/graphql-jpa-query/pull/163/files#diff-a90b759e923a8b959d1d7b5f1dd3bd80R4

Does it make sense? Is it something that you could use?

**Comment by MurrayFurtado** [comment]
@igdianov don't you need to merge in the PR to master and do another release before I can hook in to this? The PR is still in open state and unmerged.

**Comment by igdianov** [comment]
@MurrayFurtado I wanted to let this PR sit for a bit to collect use cases. You can try to use it with Jitpack in your Pom.xml:

```
  <repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
  </repositories>

<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.github.introproventures.graphql-jpa-query</groupId>
      <artifactId>graphql-jpa-query-dependencies</artifactId>
      <version>igdianov-executor-context-factory</version>
      <type>pom</type>
      <scope>import</scope>	
    </dependency>
  <dependencies>
<dependencyManagement>


```

**Comment by MurrayFurtado** [comment]
Sadly because I'm sat behind a corporate firewall I can't use Jitpack. Is there any way you could merge this feature in to master, perhaps with a feature flag if is experimental. 

Also I'm not clear on where and how to add the instrumentation code. Could you provide a skeleton example? How would I get hold of the query so I can inspect it and then send metrics to Influx.

Thanks

**Comment by MurrayFurtado** [comment]
I have tried adding this dependency to my pom but I see an error in Jenkins or locally when I try and build. In Jenkins the error is:

`09:16:05 [ERROR] Failed to execute goal on project coredata-api: Could not resolve dependencies for project com.mlp.coredata:coredata-api:jar:0.3.50: Failed to collect dependencies at com.github.introproventures.graphql-jpa-query:graphql-jpa-query-dependencies:pom:igdianov-executor-context-factory: Failed to read artifact descriptor for com.github.introproventures.graphql-jpa-query:graphql-jpa-query-dependencies:pom:igdianov-executor-context-factory: Could not transfer artifact com.github.introproventures.graphql-jpa-query:graphql-jpa-query-dependencies:pom:igdianov-executor-context-factory from/to ct-dwh-mvn-virtual (http://artifactory-ha.mlp.com/artifactory/ct-dwh-mvn-virtual): Not authorized -> [Help 1]`

If I run locally I see the following: 

' 
Downloading: https://jitpack.io/com/github/introproventures/graphql-jpa-query/graphql-jpa-query-dependencies/igdianov-executor-context-factory/graphql-jpa-query-dependencies-igdianov-executor-context-factory.pom
Oct 22, 2019 9:23:05 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443: Connection reset
Oct 22, 2019 9:23:05 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443
Oct 22, 2019 9:23:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443: Connection reset
Oct 22, 2019 9:23:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443
Oct 22, 2019 9:23:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443: Connection reset
Oct 22, 2019 9:23:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://sibcproxy.mlp.com:3128->https://jitpack.io:443
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.123 s
[INFO] Finished at: 2019-10-22T09:23:07+01:00
[INFO] Final Memory: 25M/274M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project coredata-api: Could not resolve dependencies for project com.mlp.coredata:coredata-api:jar:0.3-SNAPSHOT: Failed to collect dependencies at com.github.introproventures.graphql-jpa-query:graphql-jpa-query-dependencies:pom:igd'

Are you sure you have specified the dependency correctly?

Thanks

**Comment by MurrayFurtado** [comment]
So I have discovered that I can pull the following dependency via jitpack:
`        <dependency>
            <groupId>com.github.introproventures.graphql-jpa-query</groupId>
            <artifactId>graphql-jpa-query-dependencies</artifactId>
            <version>igdianov-executor-context-factory-gd963dd6</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>`

However this doesn't contain GraphQLJpaExecutorContextFactory.

If I go to https://javadoc.jitpack.io/com/github/introproventures/graphql-jpa-query/

I don't see anything tagged 'igdianov-executor-context-factory'  here.
