### ISSUE TITLE
Update to graphql-java v13.0

### ISSUE THREAD

**Issue by negesti** [introproventures/graphql-jpa-query#202]
Any plans to ugprade the graphql-java dependency to v13.0 ?

I have checkout the master branch and managed to compile the project again. The biggest problems i faces (so far) are: 
* The DataFetchingEnvironmentBuilder was removed
* Fields (and all properties) are immutable
If you are planning to upgrade to v13 i will try to get all tests to run/work again

**Comment by negesti** [comment]
ok, after spending some time with the custom NullValue all tests are working again

**Comment by igdianov** [comment]
@negesti Thank you for heads up! Would you be able to send a PR with the changes for Graphql-java 13.0?

**Comment by negesti** [comment]
I will create a pr tomorrow

**Comment by igdianov** [comment]
Thanks! I will take a look at it over the weekend.
