### ISSUE TITLE
How to force lower / upper on string equality check?

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#204]
I know in a previous commit you removed the lower(col_value) call to the string equality check as the default behaviour. Is it possible to override to do a case insensitive equality search?

Also I'd like to request more documentation around the framework, which could be more complete. For example you don't show how to use the AND or OR operators in your examples. 

Keep up the great work!

**Comment by igdianov** [comment]
@MurrayFurtado I can add JPA's `LOWER` and `UPPER` string equality checks to modify the default `EQ` behavior. Will it work for you?

**Comment by igdianov** [comment]
The documentation needs a lot of work. I have already started working on `Wiki` guides a few weeks ago.

**Comment by MurrayFurtado** [comment]
Really I need the ability to override the default EQ behaviour so it forces
upper or lower in certain cases. Maybe you need to add both case sensitive
and case insensitive operators for string EQ?

**Comment by igdianov** [comment]
It is not clear to me what is your use case. The EQ behavior implies exact equality check. I can add additional predicate, i.e. `LOWER' for equality check with ignore case.
