### ISSUE TITLE
How to force lower on string LIKE evaluation?

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#208]
Is it possible to also add an LIKE_LOWER operator which will force lower on the like value being evaluated in the same way as you did for string EQ? 

Thanks!

**Comment by igdianov** [comment]
@MurrayFurtado I can add `LIKE_` search predicate and all its variants ('STARTS_`, `ENDS_`  for case insensitive search criteria. I favor to use `_` suffix as a modifier to case sensitive operation. Will it work for you?

**Comment by MurrayFurtado** [comment]
Yes that would be perfect!
