### ISSUE TITLE
Bug-  default sort always applied to queries even if they don't utilise paging

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#214]
Whenever pluralized queries are generated, a default sort is always applied regardless of whether paging is required.  This is unnecessary. Can the sort ONLY be applied to paging queries please. It's a performance hit on queries which don't need it.

Thanks

**Comment by igdianov** [comment]
@MurrayFurtado The order by sort is applied for entity attribute annotated with `@Id` for primary key. It should not have significant impact on query performance in my opinion. Did you check the query plan generated by graphql query with and without default sort by primary key? What is the difference? What kind of data set size are you talking about?
