### ISSUE TITLE
Separate Connection Pools for Query vs. Mutation Operations

### ISSUE THREAD

**Issue by MENGKONGSEAN** [introproventures/graphql-jpa-query#223]
Currently I use `graphql-jpa` with `Multi-Tenancy`.
So Is it possible or not to separate data source for  `Query` and `Mutation` Operations ?
How to do it ?
**Noted** : [Currently I use `graphql-jpa` with `Multi-Tenancy` on my own project]
Thank you.

**Comment by igdianov** [comment]
Yes, you should be able to use separate datasources for query and mutations in the same JVM. However,  you have to make sure that your entity manager for PU is a proxy that creates entity manager instance per transaction request. I will update one of the examples to show how it is done.

You can also take a look at GraphQL Braid project for blue print how to stitch together Graphql microservices running in separate JVMs

**Comment by igdianov** [comment]
@MENGKONGSEAN See the updated example in https://github.com/introproventures/graphql-jpa-query/pull/228

**Comment by MENGKONGSEAN** [comment]
Thank you @igdianov .
