### ISSUE TITLE
GraphQLFieldVisibility not used

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#239]
If a `Supplier<GraphqlFieldVisibility>` Bean exists it will be autowired into the `GraphQLJpaExecutorContext`, but then it is not used.

It looks like `GraphQLJpaExecutorContext.getGraphQLSchema()` is not called by anything, should it be?

**Comment by igdianov** [comment]
@molexx Thank you for report. I will double check in a few days. I did not have time to cover this story with test cases yet. I will look into it over the weekend.
