### ISSUE TITLE
Exception when using graphql-jpa with leangen 

### ISSUE THREAD

**Issue by azizkhani** [introproventures/graphql-jpa-query#249]
I also use leangen/graphql in my project but i get this exception 

How can  id use both graphql-jpa-query and eangen/graphql 

`The bean 'graphQLExecutor', defined in class path resource [io/leangen/graphql/spqr/spring/autoconfigure/SpqrMvcAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/introproventures/graphql/jpa/query/boot/autoconfigure/GraphQLJpaQueryAutoConfiguration$DefaultGraphQLJpaQueryConfiguration.class] and overriding is disabled.`

**Comment by igdianov** [comment]
@azizkhani It looks like Leangen graphql isregistering graphQLExecutor bean with the same name in application context.
