### ISSUE TITLE
Page start 0 throws exception

### ISSUE THREAD

**Issue by whyserkan** [introproventures/graphql-jpa-query#27]
Hi, 
Thanks for this library, I have one issue if I send start value 0 I get :
request:
``` graphql
query {
  Applications(page: {start: 0, limit: 3}){
    select {
      longName
    }
    pages 
  }
}
```

``` javascript
{
  "data": {
    "Applications": null
  },
  "errors": [
    {
      "message": "Exception while fetching data (/Applications) : Negative value (-3) passed to setFirstResult",
      "path": [
        "Applications"
      ],
      "exception": {
        "cause": null,
        "stackTrace": [
          {
            "methodName": "setFirstResult",
            "fileName": "BaseQueryImpl.java",
            "lineNumber": 105,
            "className": "org.hibernate.jpa.spi.BaseQueryImpl",
            "nativeMethod": false
          },
          {
            "methodName": "setFirstResult",
            "fileName": "AbstractQueryImpl.java",
            "lineNumber": 84,
            "className": "org.hibernate.jpa.spi.AbstractQueryImpl",
            "nativeMethod": false
          },
          {
            "methodName": "setFirstResult",
            "fileName": "CriteriaQueryTypeQueryAdapter.java",
            "lineNumber": 71,
            "className": "org.hibernate.jpa.criteria.compile.CriteriaQueryTypeQueryAdapter",
            "nativeMethod": false
          },
          {
            "methodName": "get",
            "fileName": "GraphQLJpaQueryDataFetcher.java",
            "lineNumber": 103,
            "className": "com.introproventures.graphql.jpa.query.schema.impl.GraphQLJpaQueryDataFetcher",
            "nativeMethod": false
          },
          {
            "methodName": "fetchField",
            "fileName": "ExecutionStrategy.java",
            "lineNumber": 219,
            "className": "graphql.execution.ExecutionStrategy",
            "nativeMethod": false
          },
        
```

I can add full response too.
We are calling with start value 1, works fine just not follwing your readme.
Cheers

**Comment by igdianov** [comment]
@whyserkan Thank you for reporting an issue. Sorry for delay in reply - I am away on holiday at the moment. 

The start parameter for page argument is 1-based [https://github.com/introproventures/graphql-jpa-query/blob/c2f10d760b92a8bfce19413e1cfebe75416c2160/graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java#L103](see GraphQLJpaQueryDataFetcher.java#L103) and [https://github.com/introproventures/graphql-jpa-query/blob/c2f10d760b92a8bfce19413e1cfebe75416c2160/graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java#L269](StarwarsQueryExecutorTests.java#L269) 

I have updated the README to avoid the confusion.

**Comment by whyserkan** [comment]
Thank you @igdianov ,
One more thing, 
As I see 'NE' is generating a 'like' statement instead of a 'not equals'. 
Can you check it when you have time?
Cheers.
