### ISSUE TITLE
Question about row filter and Subscription example

### ISSUE THREAD

**Issue by MENGKONGSEAN** [introproventures/graphql-jpa-query#271]
Who can help me give example to how to use row filter and Subscription ?

Thank you.

**Comment by igdianov** [comment]
@MENGKONGSEAN Can you describe your use case in more detail?

**Comment by phuongphally** [comment]
@MENGKONGSEAN Awesome question.

**Comment by MENGKONGSEAN** [comment]
> @MENGKONGSEAN Can you describe your use case in more detail?

sorry our requirement  have been changed so not need for now. thank you,
