### ISSUE TITLE
Release 0.4.10 introduces caching effect

### ISSUE THREAD

**Issue by hump** [introproventures/graphql-jpa-query#273]
After upgrading to **0.4.10** we observed that changes to JPA Entities were **not reflected** in query results.
0.4.7 does not show this effect.

**Comment by igdianov** [comment]
@hump What kind of effect is it? In 0.4.10 the only changes were due to Spring Boot dependencies upgrade with newer version of the Hibernate persistence provider. Can you be more specific about the problem?

**Comment by hump** [comment]
thank you for looking into this issue :)
if we change entities in database with jpa, then these changes are not visible in the follwing queries.
Looks like a caching effect.

**Comment by hump** [comment]
@igdianov  thank you for fixing this issue :)
