### ISSUE TITLE
Mutation Wanted

### ISSUE THREAD

**Issue by kisixing** [introproventures/graphql-jpa-query#298]
Dear developers： 
  Hello everyone, I've met graphql-jpa-query in recent days. it's awesome.
  Our project needs mutation resolution. I've read issues about mutation(most information is 2 years ago), and the example URL in an answer is broken.  Would you please let me know any progress about basic Update, Delete, Create.
  Look forward your prompt reply.

**Comment by kisixing** [comment]
I'm sorry to commit the issue repeatedly  because of network problems

**Comment by fluidnotions** [comment]
@kisixing why not create it yourself, this is an open source project? What did you end up doing 2 years ago. I am planning to take a crack at implementation, but am guessing there are complications else it might have been done before subscriptions.
Searching the issues it seems the work was attempted. @igdianov can you give me some context on any challenges you faced? Am planning to track down any attempts in the git history as well. But a chat may speed things up.

**Comment by igdianov** [comment]
The mutations are outside the scope of the query side covered by this project. It is best to use Spring GraphQl/Data to implement custom mutation code and business logic.
