### ISSUE TITLE
@MappedSuperclass and @Embedded jpa annotations should be taken into account

### ISSUE THREAD

**Issue by ludovicmotte** [introproventures/graphql-jpa-query#30]
Hi,

My jpa model uses @MappedSuperclass and @Embedded jpa annotations.
It leads to a class cast exception:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.introproventures.graphql.jpa.query.web.GraphQLController': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLExecutor' defined in class path resource 
```

Could you fix that issue in a future version ?

**Comment by igdianov** [comment]
@ludovicmotte Thank you for reporting the issue. Could you provide entity model for your use case?

**Comment by ludovicmotte** [comment]
@igdianov Thanks for your reply.
[car.zip](https://github.com/introproventures/graphql-jpa-query/files/1725635/car.zip)

Car is KO because of @MappedSuperclass into Vehicule
Boat is KO because of @Embedded Engine engine

Best regards,

**Comment by igdianov** [comment]
@ludovicmotte It is an interesting case. I will take a look at it in a few days.

Did you see #1 issue related to using Lombok's `@Data` annotation to auto generate `equals()` and `hashCode()` methods on entity classes? It was the first problem I encountered and had to painfully debug for hours to realize Lombok is the cause of the problem in Hibernate.

**Comment by ludovicmotte** [comment]
@igdianov Thanks for the #1 link. It should not be an issue in my case. I think you had this issue because you model has circular references Character -> Character

**Comment by introproventures** [comment]
`@MappedSuperclass` and `@Embeddable` annotations on entity attributes need to be mapped to correctly to corresponding GraphQL query field attributes derived from JPA entity classes:

* Case 1: Given super and concrete entity classes:

```
@MappedSuperclass
@Data
public abstract class Vehicle {

    @Id
    String id;

}

@Entity(name = "Car")
@Data
@EqualsAndHashCode(callSuper=true)
public class Car extends Vehicle {

    String brand;
}

```
Should result in the following GraphQL schema:
```
type Car {
    id: String
    brand: String
}
```
The following GraphQL query `{ Car(id: "1") { id brand } }` should resolve to:
```
Car: {
    id: "1", 
    brand: "Ford"
}
```

* Case 2: Given `@Embedded` and `@Embeddable` entities:

```
@Embeddable
public class Engine {

    String identification;

}

@Entity(name = "Boat")
@Data
public class Boat  {

    @Id
    String id;

    @Embedded
    Engine engine;
}

```

Should result in the following GraphQL schema:
```
type EngineEmbeddedType {
   identification: String
}

type Boat {
    id: String
    engine: EngineEmbeddedType
}
```
The following GraphQL query `{ Boat(id: "1") { id engine { identification } } }` should resolve to:
```
Boat: {
    id: "1", 
    engine: {
        identification: "12345"
    }
}
```
