### ISSUE TITLE
Getting Started Guide?

### ISSUE THREAD

**Issue by lewimuchiri** [introproventures/graphql-jpa-query#354]
Could someone point me to a getting started guide/documentation for this library? I am using JPA with Spring Boot and want my service to expose a GraphQl API

**Describe alternatives you've considered**
Going through the examples and test classes. Could not figure out how to get started

**Comment by DBunthai** [comment]
if you would like to understand this lib, you can check on this link
https://www.graphql-java.com/documentation/getting-started

**Comment by lewimuchiri** [comment]
Hi @DBunthai, thanks. The link you've shared is for GraphQL-Java and not for GraphQL-jpa-query. What's the relationship between the two?

**Comment by igdianov** [comment]
https://github.com/introproventures/graphql-jpa-query/wiki
