### ISSUE TITLE
Bump hibernate-core from 5.6.14.Final (Nov 2022) to 6.2.1.Final (Apr 2023)

### ISSUE THREAD

**Issue by clifford-grech** [introproventures/graphql-jpa-query#364]
**Is your feature request related to a problem? Please describe.**

Since the project is still using Hibernate-core version 5.6.14.Final and javax.persistence-api version 2.2, we are constrained to feeding it JPA entity models using the old javax.persistence-api library which was released back in August 2017. We would like to make use of your library, but this is causing us problems with getting clearance from our security department.

The JPA project has since been transferred to the Jakarta namespace and the latest version is 3.1.0, which is what hibernate-core version 6.2.1 supports.

We recommend the following upgrades:

- javax.interceptor-api - 1.2.2 (Mar 2018) to jakarta.interceptor-api - 2.1.0 (Apr 2022)
- javax.persistence-api - 2.2 (Aug 2017) to jakarta.persistence-api - 3.1.0 (Apr 2022)
- javax.transaction-api - 1.3 (Mar 2018) to jakarta.transaction-api - 2.0.1 - (Mar 2022)
- hibernate-core - 5.6.14.Final (Nov 2022) to 6.2.1.Final (Apr 2023) 
- spring-boot-dependencies - 2.7.6 (Nov 2022) to 3.0.5 (Mar 2023)
- spring-core - 5.3.24 (Nov 2022) to 6.0.8 (Apr 2023)

**Describe the solution you'd like**
Bump the version of hibernate-core to 6.2.1.Final and resolve any transitive dependencies.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by igdianov** [comment]
You can now use version 1.0.x with support for JPA 3.1, Jakarta EE, and Spring Boot 3: https://github.com/introproventures/graphql-jpa-query/releases/tag/1.0.0
