### ISSUE TITLE
Make example running on Play With Docker 

### ISSUE THREAD

**Issue by igdianov** [introproventures/graphql-jpa-query#7]
Create Dockerfile for `graphql-jpa-query-example` Spring Boot application.
Add Dockerfile image build and publish to Docker Hub on Maven `deploy` goal.
Create PWD badge link in README in order to run the provided example on https://play-with-docker.com.

**Comment by almerico** [comment]
play_with_docker branch added
to build docker image-  mvn clean package docker:build -DskipTests   (docker environment variables have to be set correctly)
push image docker push introproventures/graphql-jpa-query

for local test - docker stack deploy --compose-file docker-compose.yml graphql
At the end of Readme file new Docker section with link to play-with-docker.com 
https://github.com/introproventures/graphql-jpa-query/blob/play_with_doker/README.md

**Comment by igdianov** [comment]
Done
