### ISSUE TITLE
Add to the executor's context

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#75]
Now we have schema merging we can add non-JPA functionality to our projects. Sometimes that functionality needs some things in the context - set in the executor and available from `DataFetchingEnvironment`. But graphql-jpa-query defines the Executor which runs all calls and I don't see how to modify that context without breaking it.

In my particular case I need the HttpServletRequest used to make the query call. Maybe other use cases might want to add their own things in there?

**Comment by igdianov** [comment]
@molexx I think I can expose `ExecutionContext` via Builder Factory, so you could inject your own stuff in it easily as well as access `HttpServletRequest`. The reason it is closed is that I had to make a hack in earlier `graphql-java` library version to inject variables value for resolving bindings in reverse query fields. I think in `graphql-java:11` I can now resolve variables without that hack and expose `ExecutionContext` customization for schema extensions. 

Stay tuned for PR.
