### ISSUE TITLE
Query help: filter inside relationships without returning data

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#76]
Say I want to find all Humans who have a relationship with a Droid which appeared in A New Hope.
The README has this:
```
query {
    Humans {
        select {
            name
            favoriteDroid(where: {appearsIn: {IN:[A_NEW_HOPE]}}) {
            	name
          	}
        }
    }
}
```

Which returns:
```
{
  "Humans": {
    "select": [
      {
        "name": "Luke Skywalker",
        "favoriteDroid": {
          "name": "C-3PO"
        }
      },
      {
        "name": "Darth Vader",
        "favoriteDroid": {
          "name": "R2-D2"
        }
      }
    ]
  }
```

but, I just want the Humans. I don't want any info on the Droids. Sure, it works, I can just look at the top-level Humans but there's a load of nested JSON I don't want which will get created, sent over the network and parsed. (In our real db this is much bigger!)
In the query above I have to provide at least one Droid field - either empty braces or removing the braces fails graphiql's schema validation.

Am I missing a way to do this?

Thanks.

**Comment by igdianov** [comment]
@molexx It is a requirement in GraphQL spec to specify a field inside composite field, i.e. the composite field cannot be empty. 

What you are looking for should be something like this (with implicit `where: {}` schema generated for JPA entity attributes) :

```
query {
    Humans(where: { favoriteDroid( appearsIn: {IN:[A_NEW_HOPE]}} ) ) {
        select {
            name
        }
    }
}
```
It should be possible refactor schema builder and query data fetcher to do something like this. Do you want create a PR with a failing test case, so we could both take on it?

**Comment by molexx** [comment]
Sure. Is there a tricky reason why relationships are currently excluded from where clauses?

**Comment by igdianov** [comment]
> Sure. Is there a tricky reason why relationships are currently excluded from where clauses?

@molexx I vaguely remember there was a problem in earlier graphq-java library that was limiting the exposure of root DataFetching context. It is not a problem anymore in version 11.

**Comment by molexx** [comment]
I'm making some progress but need some pointers please...

What's the best way to handle this around `QraphQLJpaBaseDataFetcher.getFieldPredicate()`? It's possible to recurse along the Fields until a Criteria (the 'IN' in the above example) is reached but `PredicateFilter` doesn't handle multiple fields nor have any notion of a parent/child hierarchy. Might building up a JPA path String, using dots to separate entities/properties, be a sufficient way to do it?

If so, that's failing currently at `path.get(it.getField())` because it's not one Field any more but a dot-separated reference:
` Unable to locate Attribute  with the the given name [favoriteDroid.appearsIn] on this ManagedType [com.introproventures.graphql.jpa.query.example.starwars.Character]`

**Comment by molexx** [comment]
@igdianov do you have a moment to have a look at this please? I'd like to implement it but need some pointers! Thanks

**Comment by igdianov** [comment]
@molexx I will take a look.

**Comment by molexx** [comment]
Great, thanks! I'll try it out.
