### ISSUE TITLE
Having 2 entities embedding common shared entity fails

### ISSUE THREAD

**Issue by darkrift** [introproventures/graphql-jpa-query#91]
I have 2 entities embedding a 3rd entity which leads to the following error :

No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'AddressEmbeddableType' from being a 'GraphQLObjectType' to a 'GraphQLObjectType'

In spring, EmbeddableTypeImpl doesn't implement hashcode nor equals for which GraphQLJpaSchemaBuilder fails to retrieve the proper type from the input or output cache in getEmbeddableType(EmbeddableType<?> embeddableType, boolean input) and thus a new type is created for the same shared embedded type.

**Comment by igdianov** [comment]
@darkrift Can you post the minimal entity schema that causes the error?

**Comment by darkrift** [comment]
https://gist.github.com/darkrift/424ec218e7481c342703e180829029c0

**Comment by igdianov** [comment]
@darkrift Thank you! I will take a look.

**Comment by darkrift** [comment]
Something to also keep in mind while handling this is the attributesoverride mapping, for instance : 
    @AttributeOverrides(value = {
            @AttributeOverride(name = "address1", column = @Column(name = "adresse1")),
            @AttributeOverride(name = "address2", column = @Column(name = "adresse2")),
            @AttributeOverride(name = "codePostal", column = @Column(name = "code_postal"))
    })

**Comment by darkrift** [comment]
Another use case to take into consideration is if we embed the same object, multiple time on the same entity as well. For instance, if we wanted to represent a phone number by an embedded object and mapped on a different column.

**Comment by igdianov** [comment]
@darkrift I already made some changes locally to fix the problem. It should be fixed in the next release.
