### ISSUE TITLE
0.3.14 regression: spring.graphql.jpa.query.path must be specified now

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#93]
Not a high priority as there's a simple solution... but 0.3.14 refuses to start up because `spring.graphql.jpa.query.path` is not defined. Which is odd because it is defined in `default.properties` which is referenced by `GraphQLJpaQueryProperties`. I have both `graphql-jpa-query-autoconfigure` and `graphql-jpa-query-boot-starter` as dependencies.

Simple workaround foe now is to add:  
`spring.graphql.jpa.query.path: /graphql`
to the enclosing application's properties.

**Comment by igdianov** [comment]
@molexx Thank you for reporting this. I will take a look.

**Comment by igdianov** [comment]
@molexx fixed in 0.3.15
