### ISSUE TITLE
Nested relationship queries in where clauses

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#97]
In a top level where clause you can only use a relationship of the first entity, after that you can only use simple attributes not relationships.

For example:
```
query {  
  Books(where: {
    author: {id: {EQ: 1}}
  }) {
    select {
      id
      title
      genre
      author {
        id
        name
      }
    }
  }
}
```
you can say '`author: {id: `' but you can't say '`author: {books: `'.
Would it be possible to allow this please?

There are comments on this in #96.

**Comment by molexx** [comment]
RE https://github.com/introproventures/graphql-jpa-query/pull/96#issuecomment-472544018, just thinking out loud on how this might work:

How about walking the tree in the where clause and storing up the defined predicates for entities that are not in the initial select. Then as the rest of the query/sub queries are built from the projection selection, check to see if there is a predicate stored for the current entity and apply it.
If, after all the nested queries are built, there are unapplied predicates remaining, generate clauses/sub queries to satisfy them.

?

**Comment by igdianov** [comment]
@molexx I have created a PR to add support for nested relationships in where criteria expressions. See: https://github.com/introproventures/graphql-jpa-query/pull/108/files#diff-52f280238db11c302ce9ac4f3fc76b15R777. 

It only supports `to one` relationships for now.
